# Generated by Django 4.1 on 2024-07-04 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_location',
            },
        ),
        migrations.CreateModel(
            name='TrainingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_part',
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_type',
            },
        ),
        migrations.CreateModel(
            name='UserCustomMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=1000, verbose_name='メニュー名')),
                ('menu_details', models.CharField(blank=True, max_length=2000, null=True, verbose_name='詳細')),
                ('reference_video_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='動画URL')),
                ('reference_site_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='サイトURL')),
                ('last_performed_date', models.CharField(default='未実施', max_length=1000, verbose_name='最終実施日')),
                ('is_current', models.BooleanField(default=False, verbose_name='現在選択')),
                ('day_of_week', models.CharField(blank=True, choices=[('monday', '月曜日'), ('tuesday', '火曜日'), ('wednesday', '水曜日'), ('thursday', '木曜日'), ('friday', '金曜日'), ('saturday', '土曜日'), ('sunday', '日曜日'), ('free', 'フリー')], max_length=10, null=True, verbose_name='曜日')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('training_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training_menus.traininglocation', verbose_name='場所')),
                ('training_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training_menus.trainingpart', verbose_name='対象部位')),
                ('training_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training_menus.trainingtype', verbose_name='トレーニングタイプ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_menus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザーカスタムメニュー',
                'verbose_name_plural': 'ユーザーカスタムメニュー',
                'db_table': 'training_custom_menus',
            },
        ),
    ]
