# Generated by Django 4.1 on 2024-07-10 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_menus', '0001_add_trainingmenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommenus',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('free', 'フリー'), ('monday', '月曜日'), ('tuesday', '火曜日'), ('wednesday', '水曜日'), ('thursday', '木曜日'), ('friday', '金曜日'), ('saturday', '土曜日'), ('sunday', '日曜日')], max_length=10, null=True, verbose_name='曜日'),
        ),
        migrations.CreateModel(
            name='TrainingGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='トレーニング目標')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_goals',
            },
        ),
    ]
